### ISSUE TITLE
Redesign the UI

### ISSUE THREAD

**Issue by bobmayuze** [bobmayuze/Vercipe#36]
DDL: MAR 25th

**Comment by bobmayuze** [comment]
make sure we have the same layout margin as GitHub does. Make the page shorter @limaa1

**Comment by alimabean** [comment]
March 22: updated most of ui

content now overflows in it's parent container, ie, scrolling a section will not move the header or other content on page

**Comment by alimabean** [comment]
Still need to:
- adjust layout margins
- add `recommended` widget in place of search bar on lefthand side
- redesign search bar and add to top of recipe list

**Comment by bobmayuze** [comment]
I'm assuming the re-design is done by now? @limaa1

**Comment by alimabean** [comment]
Yes the redesign for this sprint can be considered done, of course I'm open to more suggestions and improvements

**Comment by bobmayuze** [comment]
I was thinking we could make the footer into the Github style, what do u guys think?

**Comment by alimabean** [comment]
Sounds good, do you want to keep the footer fixed in place?

**Comment by bobmayuze** [comment]
yeah, I'm fine with the fixed in place style, but I feel like we can make it centered instead of separated
