### ISSUE TITLE
Use a user modal for user to login/signUp

### ISSUE THREAD

**Issue by bobmayuze** [bobmayuze/Vercipe#38]
Use a user modal for user to login/signUp

**Comment by bobmayuze** [comment]
For reference : [example](https://www.w3schools.com/howto/howto_css_login_form.asp)

**Comment by bobmayuze** [comment]
@Rockpath

**Comment by tmacintosh96** [comment]
@bobmayuze How can I change the css of a div class from the ts file?

**Comment by bobmayuze** [comment]
You may modify the CSS of the component file. Each component has its own CSS file. @Rockpath

**Comment by tmacintosh96** [comment]
@bobmayuze yeah, I am aware, but what I am trying to do is get the usar modal to show/hide depending on whether the user is logged in or not and if they clicked the icon on the top right. Also if they click outside the usar modal, it will hide itself again, like the example you provided.

**Comment by bobmayuze** [comment]
@Rockpath  Yes, that is what we need. You can use ngIf to determine if the user is logged in or not.
