### ISSUE TITLE
User Logout function 

### ISSUE THREAD

**Issue by bobmayuze** [bobmayuze/Vercipe#8]
We need an endpoint for logging out.

**Comment by bobmayuze** [comment]
@Rockpath

**Comment by tmacintosh96** [comment]
@bobmayuze So since this is a frontend label, does that mean that I only need to have the logout function working on frontend via button or do I need to add it to the backend files (for instance the user.js files) as well?

**Comment by bobmayuze** [comment]
@Rockpath Yes
